import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { 
  Scale, ArrowLeft, FileText, Download, Search, Filter,
  File, FileCheck, FileWarning, Briefcase, Home as HomeIcon, Users, Heart, X
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';

interface Template {
  id: string;
  template_name: string;
  template_name_bn: string | null;
  category: string;
  template_type: string;
  template_content: string;
  tags: string[] | null;
  fields?: TemplateField[];
}

interface TemplateField {
  name: string;
  label: string;
  label_bn?: string;
  type: 'text' | 'date' | 'textarea';
  required?: boolean;
}

const templateCategories = [
  { id: 'all', name: 'All Templates', icon: FileText },
  { id: 'criminal', name: 'Criminal Law', icon: FileWarning },
  { id: 'civil', name: 'Civil Law', icon: FileCheck },
  { id: 'property', name: 'Property', icon: HomeIcon },
  { id: 'family', name: 'Family Law', icon: Heart },
  { id: 'business', name: 'Business', icon: Briefcase },
  { id: 'employment', name: 'Employment', icon: Users },
];

const sampleTemplates: Template[] = [
  {
    id: '1',
    template_name: 'First Information Report (FIR)',
    template_name_bn: 'প্রথম তথ্য প্রতিবেদন',
    category: 'criminal',
    template_type: 'FIR',
    template_content: `FIRST INFORMATION REPORT (FIR)
Under Section 154 Cr.P.C.

Police Station: {{police_station}}
District: {{district}}
Date: {{date}}

1. Complainant's Name: {{complainant_name}}
   Father's/Husband's Name: {{father_name}}
   Address: {{complainant_address}}
   Phone: {{phone}}

2. Date & Time of Occurrence: {{occurrence_date}}
3. Place of Occurrence: {{occurrence_place}}

4. Description of Offense:
{{offense_description}}

5. Name & Description of Accused (if known):
{{accused_details}}

6. Witnesses:
{{witnesses}}

7. Action Requested:
I request you to register this FIR and take necessary legal action against the accused person(s).

Signature of Complainant: ____________________
Date: {{date}}

---
Generated by JurisMind | Created by RONY`,
    tags: ['criminal', 'police', 'complaint'],
    fields: [
      { name: 'police_station', label: 'Police Station', label_bn: 'থানা', type: 'text', required: true },
      { name: 'district', label: 'District', label_bn: 'জেলা', type: 'text', required: true },
      { name: 'date', label: 'Date', label_bn: 'তারিখ', type: 'date', required: true },
      { name: 'complainant_name', label: 'Complainant Name', label_bn: 'অভিযোগকারীর নাম', type: 'text', required: true },
      { name: 'father_name', label: "Father's/Husband's Name", label_bn: 'পিতা/স্বামীর নাম', type: 'text', required: true },
      { name: 'complainant_address', label: 'Address', label_bn: 'ঠিকানা', type: 'textarea', required: true },
      { name: 'phone', label: 'Phone Number', label_bn: 'ফোন নম্বর', type: 'text' },
      { name: 'occurrence_date', label: 'Date & Time of Occurrence', label_bn: 'ঘটনার তারিখ ও সময়', type: 'text', required: true },
      { name: 'occurrence_place', label: 'Place of Occurrence', label_bn: 'ঘটনাস্থল', type: 'text', required: true },
      { name: 'offense_description', label: 'Description of Offense', label_bn: 'অপরাধের বিবরণ', type: 'textarea', required: true },
      { name: 'accused_details', label: 'Accused Details', label_bn: 'অভিযুক্তের বিবরণ', type: 'textarea' },
      { name: 'witnesses', label: 'Witnesses', label_bn: 'সাক্ষী', type: 'textarea' },
    ],
  },
  {
    id: '2',
    template_name: 'Legal Notice',
    template_name_bn: 'আইনি নোটিশ',
    category: 'civil',
    template_type: 'Notice',
    template_content: `LEGAL NOTICE

Date: {{date}}

To,
{{recipient_name}}
{{recipient_address}}

Subject: Legal Notice for {{subject}}

Dear Sir/Madam,

Under instructions from my client, {{client_name}}, residing at {{client_address}}, I do hereby serve upon you the following Legal Notice:

FACTS OF THE CASE:
{{facts}}

LEGAL GROUNDS:
{{legal_grounds}}

DEMAND:
{{demand}}

You are hereby called upon to {{action_required}} within {{days}} days from the receipt of this notice, failing which my client shall be constrained to initiate appropriate legal proceedings against you in the competent court of law, at your risk and cost.

Please treat this notice as final.

Yours faithfully,

{{lawyer_name}}
Advocate
{{bar_council_number}}

---
Generated by JurisMind | Created by RONY`,
    tags: ['notice', 'demand', 'civil'],
    fields: [
      { name: 'date', label: 'Date', label_bn: 'তারিখ', type: 'date', required: true },
      { name: 'recipient_name', label: 'Recipient Name', label_bn: 'প্রাপকের নাম', type: 'text', required: true },
      { name: 'recipient_address', label: 'Recipient Address', label_bn: 'প্রাপকের ঠিকানা', type: 'textarea', required: true },
      { name: 'subject', label: 'Subject', label_bn: 'বিষয়', type: 'text', required: true },
      { name: 'client_name', label: 'Client Name', label_bn: 'মক্কেলের নাম', type: 'text', required: true },
      { name: 'client_address', label: 'Client Address', label_bn: 'মক্কেলের ঠিকানা', type: 'textarea', required: true },
      { name: 'facts', label: 'Facts of the Case', label_bn: 'মামলার তথ্য', type: 'textarea', required: true },
      { name: 'legal_grounds', label: 'Legal Grounds', label_bn: 'আইনি ভিত্তি', type: 'textarea', required: true },
      { name: 'demand', label: 'Demand', label_bn: 'দাবি', type: 'textarea', required: true },
      { name: 'action_required', label: 'Action Required', label_bn: 'প্রয়োজনীয় পদক্ষেপ', type: 'text', required: true },
      { name: 'days', label: 'Days to Respond', label_bn: 'জবাব দেওয়ার দিন', type: 'text', required: true },
      { name: 'lawyer_name', label: 'Lawyer Name', label_bn: 'আইনজীবীর নাম', type: 'text', required: true },
      { name: 'bar_council_number', label: 'Bar Council Number', label_bn: 'বার কাউন্সিল নম্বর', type: 'text' },
    ],
  },
  {
    id: '3',
    template_name: 'Power of Attorney',
    template_name_bn: 'মুখতারনামা',
    category: 'business',
    template_type: 'POA',
    template_content: `POWER OF ATTORNEY

KNOW ALL MEN BY THESE PRESENTS:

I, {{principal_name}}, son/daughter of {{principal_father}}, residing at {{principal_address}}, do hereby appoint and constitute {{attorney_name}}, son/daughter of {{attorney_father}}, residing at {{attorney_address}}, as my true and lawful Attorney.

PURPOSE:
To act on my behalf for the following purposes:
{{purposes}}

POWERS GRANTED:
{{powers}}

VALIDITY:
This Power of Attorney shall remain valid from {{start_date}} to {{end_date}} unless revoked earlier in writing.

IN WITNESS WHEREOF, I have hereunto set my hand and seal on this {{date}}.

Principal: ____________________
({{principal_name}})

WITNESSES:
1. Name: {{witness1_name}}
   Address: {{witness1_address}}
   Signature: ____________________

2. Name: {{witness2_name}}
   Address: {{witness2_address}}
   Signature: ____________________

---
Generated by JurisMind | Created by RONY`,
    tags: ['power', 'attorney', 'authorization'],
    fields: [
      { name: 'principal_name', label: 'Principal Name', label_bn: 'মূল ব্যক্তির নাম', type: 'text', required: true },
      { name: 'principal_father', label: "Principal's Father's Name", label_bn: 'পিতার নাম', type: 'text', required: true },
      { name: 'principal_address', label: 'Principal Address', label_bn: 'ঠিকানা', type: 'textarea', required: true },
      { name: 'attorney_name', label: 'Attorney Name', label_bn: 'মুখতারের নাম', type: 'text', required: true },
      { name: 'attorney_father', label: "Attorney's Father's Name", label_bn: 'মুখতারের পিতার নাম', type: 'text', required: true },
      { name: 'attorney_address', label: 'Attorney Address', label_bn: 'মুখতারের ঠিকানা', type: 'textarea', required: true },
      { name: 'purposes', label: 'Purposes', label_bn: 'উদ্দেশ্য', type: 'textarea', required: true },
      { name: 'powers', label: 'Powers Granted', label_bn: 'প্রদত্ত ক্ষমতা', type: 'textarea', required: true },
      { name: 'start_date', label: 'Start Date', label_bn: 'শুরুর তারিখ', type: 'date', required: true },
      { name: 'end_date', label: 'End Date', label_bn: 'শেষ তারিখ', type: 'date', required: true },
      { name: 'date', label: 'Signing Date', label_bn: 'স্বাক্ষরের তারিখ', type: 'date', required: true },
      { name: 'witness1_name', label: 'Witness 1 Name', label_bn: 'সাক্ষী ১ এর নাম', type: 'text', required: true },
      { name: 'witness1_address', label: 'Witness 1 Address', label_bn: 'সাক্ষী ১ এর ঠিকানা', type: 'text', required: true },
      { name: 'witness2_name', label: 'Witness 2 Name', label_bn: 'সাক্ষী ২ এর নাম', type: 'text', required: true },
      { name: 'witness2_address', label: 'Witness 2 Address', label_bn: 'সাক্ষী ২ এর ঠিকানা', type: 'text', required: true },
    ],
  },
  {
    id: '4',
    template_name: 'Rental Agreement',
    template_name_bn: 'ভাড়া চুক্তি',
    category: 'property',
    template_type: 'Agreement',
    template_content: `RENTAL AGREEMENT

This Rental Agreement is made on {{date}} between:

LANDLORD:
Name: {{landlord_name}}
Father's Name: {{landlord_father}}
Address: {{landlord_address}}
NID: {{landlord_nid}}

AND

TENANT:
Name: {{tenant_name}}
Father's Name: {{tenant_father}}
Permanent Address: {{tenant_permanent_address}}
NID: {{tenant_nid}}

PROPERTY DETAILS:
Address: {{property_address}}
Type: {{property_type}}
Area: {{property_area}}

TERMS AND CONDITIONS:

1. RENT: Monthly rent of BDT {{monthly_rent}} ({{rent_in_words}}) payable by the {{payment_date}} of each month.

2. SECURITY DEPOSIT: BDT {{security_deposit}} ({{deposit_in_words}}) paid in advance, refundable upon termination.

3. TENURE: {{tenure_months}} months starting from {{start_date}} to {{end_date}}.

4. UTILITIES: {{utilities_terms}}

5. MAINTENANCE: {{maintenance_terms}}

6. TERMINATION: Either party may terminate with {{notice_period}} days written notice.

7. ADDITIONAL TERMS:
{{additional_terms}}

SIGNATURES:

Landlord: ____________________          Tenant: ____________________
({{landlord_name}})                     ({{tenant_name}})

WITNESSES:
1. {{witness1_name}}                    2. {{witness2_name}}

---
Generated by JurisMind | Created by RONY`,
    tags: ['rent', 'lease', 'property'],
    fields: [
      { name: 'date', label: 'Agreement Date', label_bn: 'চুক্তির তারিখ', type: 'date', required: true },
      { name: 'landlord_name', label: 'Landlord Name', label_bn: 'বাড়িওয়ালার নাম', type: 'text', required: true },
      { name: 'landlord_father', label: "Landlord's Father's Name", label_bn: 'বাড়িওয়ালার পিতার নাম', type: 'text', required: true },
      { name: 'landlord_address', label: 'Landlord Address', label_bn: 'বাড়িওয়ালার ঠিকানা', type: 'textarea', required: true },
      { name: 'landlord_nid', label: 'Landlord NID', label_bn: 'বাড়িওয়ালার এনআইডি', type: 'text' },
      { name: 'tenant_name', label: 'Tenant Name', label_bn: 'ভাড়াটিয়ার নাম', type: 'text', required: true },
      { name: 'tenant_father', label: "Tenant's Father's Name", label_bn: 'ভাড়াটিয়ার পিতার নাম', type: 'text', required: true },
      { name: 'tenant_permanent_address', label: 'Tenant Permanent Address', label_bn: 'স্থায়ী ঠিকানা', type: 'textarea', required: true },
      { name: 'tenant_nid', label: 'Tenant NID', label_bn: 'ভাড়াটিয়ার এনআইডি', type: 'text' },
      { name: 'property_address', label: 'Property Address', label_bn: 'সম্পত্তির ঠিকানা', type: 'textarea', required: true },
      { name: 'property_type', label: 'Property Type', label_bn: 'সম্পত্তির ধরন', type: 'text', required: true },
      { name: 'property_area', label: 'Property Area', label_bn: 'আয়তন', type: 'text' },
      { name: 'monthly_rent', label: 'Monthly Rent (BDT)', label_bn: 'মাসিক ভাড়া', type: 'text', required: true },
      { name: 'rent_in_words', label: 'Rent in Words', label_bn: 'কথায় ভাড়া', type: 'text', required: true },
      { name: 'payment_date', label: 'Payment Due Date', label_bn: 'পরিশোধের তারিখ', type: 'text', required: true },
      { name: 'security_deposit', label: 'Security Deposit (BDT)', label_bn: 'জামানত', type: 'text', required: true },
      { name: 'deposit_in_words', label: 'Deposit in Words', label_bn: 'কথায় জামানত', type: 'text', required: true },
      { name: 'tenure_months', label: 'Tenure (Months)', label_bn: 'মেয়াদ (মাস)', type: 'text', required: true },
      { name: 'start_date', label: 'Start Date', label_bn: 'শুরুর তারিখ', type: 'date', required: true },
      { name: 'end_date', label: 'End Date', label_bn: 'শেষ তারিখ', type: 'date', required: true },
      { name: 'utilities_terms', label: 'Utilities Terms', label_bn: 'ইউটিলিটি শর্ত', type: 'textarea' },
      { name: 'maintenance_terms', label: 'Maintenance Terms', label_bn: 'রক্ষণাবেক্ষণ শর্ত', type: 'textarea' },
      { name: 'notice_period', label: 'Notice Period (Days)', label_bn: 'নোটিশ সময়কাল', type: 'text', required: true },
      { name: 'additional_terms', label: 'Additional Terms', label_bn: 'অতিরিক্ত শর্ত', type: 'textarea' },
      { name: 'witness1_name', label: 'Witness 1 Name', label_bn: 'সাক্ষী ১', type: 'text', required: true },
      { name: 'witness2_name', label: 'Witness 2 Name', label_bn: 'সাক্ষী ২', type: 'text', required: true },
    ],
  },
  {
    id: '5',
    template_name: 'Divorce Notice (Muslim Family Law)',
    template_name_bn: 'তালাক নোটিশ',
    category: 'family',
    template_type: 'Notice',
    template_content: `NOTICE OF TALAQ
Under Section 7 of the Muslim Family Laws Ordinance, 1961

Date: {{date}}

To,
The Chairman
Union Parishad/Municipality: {{union_parishad}}
Upazila: {{upazila}}
District: {{district}}

Subject: Notice of Talaq

Sir,

I, {{husband_name}}, son of {{husband_father}}, residing at {{husband_address}}, do hereby give notice that I have pronounced Talaq upon my wife, {{wife_name}}, daughter of {{wife_father}}, on {{talaq_date}}.

Details of Marriage:
- Date of Marriage: {{marriage_date}}
- Place of Marriage: {{marriage_place}}
- Kabin Amount: BDT {{kabin_amount}}

Reasons for Talaq:
{{reasons}}

I am sending a copy of this notice to my wife at the following address:
{{wife_address}}

I understand that:
1. This Talaq shall not be effective until 90 days from the receipt of this notice.
2. During this period, reconciliation may be attempted through the Arbitration Council.

Signature: ____________________
{{husband_name}}
NID: {{husband_nid}}
Phone: {{husband_phone}}

---
Generated by JurisMind | Created by RONY`,
    tags: ['divorce', 'family', 'muslim'],
    fields: [
      { name: 'date', label: 'Date', label_bn: 'তারিখ', type: 'date', required: true },
      { name: 'union_parishad', label: 'Union Parishad/Municipality', label_bn: 'ইউনিয়ন পরিষদ', type: 'text', required: true },
      { name: 'upazila', label: 'Upazila', label_bn: 'উপজেলা', type: 'text', required: true },
      { name: 'district', label: 'District', label_bn: 'জেলা', type: 'text', required: true },
      { name: 'husband_name', label: 'Husband Name', label_bn: 'স্বামীর নাম', type: 'text', required: true },
      { name: 'husband_father', label: "Husband's Father's Name", label_bn: 'স্বামীর পিতার নাম', type: 'text', required: true },
      { name: 'husband_address', label: 'Husband Address', label_bn: 'স্বামীর ঠিকানা', type: 'textarea', required: true },
      { name: 'wife_name', label: 'Wife Name', label_bn: 'স্ত্রীর নাম', type: 'text', required: true },
      { name: 'wife_father', label: "Wife's Father's Name", label_bn: 'স্ত্রীর পিতার নাম', type: 'text', required: true },
      { name: 'wife_address', label: 'Wife Address', label_bn: 'স্ত্রীর ঠিকানা', type: 'textarea', required: true },
      { name: 'talaq_date', label: 'Date of Talaq', label_bn: 'তালাকের তারিখ', type: 'date', required: true },
      { name: 'marriage_date', label: 'Marriage Date', label_bn: 'বিবাহের তারিখ', type: 'date', required: true },
      { name: 'marriage_place', label: 'Marriage Place', label_bn: 'বিবাহের স্থান', type: 'text', required: true },
      { name: 'kabin_amount', label: 'Kabin Amount (BDT)', label_bn: 'কাবিন', type: 'text', required: true },
      { name: 'reasons', label: 'Reasons for Talaq', label_bn: 'তালাকের কারণ', type: 'textarea', required: true },
      { name: 'husband_nid', label: 'Husband NID', label_bn: 'স্বামীর এনআইডি', type: 'text' },
      { name: 'husband_phone', label: 'Husband Phone', label_bn: 'ফোন নম্বর', type: 'text' },
    ],
  },
  {
    id: '6',
    template_name: 'Employment Contract',
    template_name_bn: 'চাকরির চুক্তি',
    category: 'employment',
    template_type: 'Contract',
    template_content: `EMPLOYMENT CONTRACT

This Employment Contract is entered into on {{date}} between:

EMPLOYER:
Company Name: {{company_name}}
Address: {{company_address}}
Represented by: {{employer_rep}}
Designation: {{employer_designation}}

AND

EMPLOYEE:
Name: {{employee_name}}
Father's Name: {{employee_father}}
Address: {{employee_address}}
NID: {{employee_nid}}

TERMS OF EMPLOYMENT:

1. POSITION: {{position}}
2. DEPARTMENT: {{department}}
3. START DATE: {{start_date}}
4. PROBATION PERIOD: {{probation_months}} months

5. COMPENSATION:
   - Basic Salary: BDT {{basic_salary}}/month
   - House Rent: BDT {{house_rent}}/month
   - Medical Allowance: BDT {{medical}}/month
   - Transport: BDT {{transport}}/month
   - Total: BDT {{total_salary}}/month

6. WORKING HOURS: {{working_hours}}
7. LEAVE ENTITLEMENT: {{leave_entitlement}}

8. DUTIES AND RESPONSIBILITIES:
{{duties}}

9. CONFIDENTIALITY:
The Employee agrees to maintain confidentiality of all proprietary information.

10. TERMINATION:
Either party may terminate with {{notice_period}} days written notice.

SIGNATURES:

For Employer: ____________________     Employee: ____________________
({{employer_rep}})                     ({{employee_name}})

Date: {{date}}

---
Generated by JurisMind | Created by RONY`,
    tags: ['employment', 'job', 'contract'],
    fields: [
      { name: 'date', label: 'Contract Date', label_bn: 'চুক্তির তারিখ', type: 'date', required: true },
      { name: 'company_name', label: 'Company Name', label_bn: 'কোম্পানির নাম', type: 'text', required: true },
      { name: 'company_address', label: 'Company Address', label_bn: 'কোম্পানির ঠিকানা', type: 'textarea', required: true },
      { name: 'employer_rep', label: 'Employer Representative', label_bn: 'নিয়োগকর্তার প্রতিনিধি', type: 'text', required: true },
      { name: 'employer_designation', label: 'Employer Designation', label_bn: 'পদবী', type: 'text', required: true },
      { name: 'employee_name', label: 'Employee Name', label_bn: 'কর্মচারীর নাম', type: 'text', required: true },
      { name: 'employee_father', label: "Employee's Father's Name", label_bn: 'পিতার নাম', type: 'text', required: true },
      { name: 'employee_address', label: 'Employee Address', label_bn: 'ঠিকানা', type: 'textarea', required: true },
      { name: 'employee_nid', label: 'Employee NID', label_bn: 'এনআইডি', type: 'text' },
      { name: 'position', label: 'Position', label_bn: 'পদ', type: 'text', required: true },
      { name: 'department', label: 'Department', label_bn: 'বিভাগ', type: 'text', required: true },
      { name: 'start_date', label: 'Start Date', label_bn: 'শুরুর তারিখ', type: 'date', required: true },
      { name: 'probation_months', label: 'Probation Period (Months)', label_bn: 'শিক্ষানবিশ সময়কাল', type: 'text', required: true },
      { name: 'basic_salary', label: 'Basic Salary', label_bn: 'মূল বেতন', type: 'text', required: true },
      { name: 'house_rent', label: 'House Rent', label_bn: 'বাড়ি ভাড়া', type: 'text' },
      { name: 'medical', label: 'Medical Allowance', label_bn: 'চিকিৎসা ভাতা', type: 'text' },
      { name: 'transport', label: 'Transport Allowance', label_bn: 'যাতায়াত ভাতা', type: 'text' },
      { name: 'total_salary', label: 'Total Salary', label_bn: 'মোট বেতন', type: 'text', required: true },
      { name: 'working_hours', label: 'Working Hours', label_bn: 'কর্মঘণ্টা', type: 'text', required: true },
      { name: 'leave_entitlement', label: 'Leave Entitlement', label_bn: 'ছুটির অধিকার', type: 'text', required: true },
      { name: 'duties', label: 'Duties and Responsibilities', label_bn: 'দায়িত্ব ও কর্তব্য', type: 'textarea', required: true },
      { name: 'notice_period', label: 'Notice Period (Days)', label_bn: 'নোটিশ সময়কাল', type: 'text', required: true },
    ],
  },
  {
    id: '7',
    template_name: 'Affidavit',
    template_name_bn: 'হলফনামা',
    category: 'civil',
    template_type: 'Affidavit',
    template_content: `AFFIDAVIT

I, {{deponent_name}}, son/daughter of {{deponent_father}}, aged {{age}} years, by faith {{religion}}, by profession {{profession}}, residing at {{deponent_address}}, do hereby solemnly affirm and declare as follows:

1. That I am a citizen of Bangladesh and competent to make this affidavit.

2. That I am making this affidavit for the purpose of {{purpose}}.

3. {{statement_1}}

4. {{statement_2}}

5. {{statement_3}}

6. That the statements made above are true to the best of my knowledge and belief, and nothing material has been concealed therefrom.

DEPONENT

Solemnly affirmed before me on this {{date}} at {{place}}.

Notary Public / Oath Commissioner

---
Generated by JurisMind | Created by RONY`,
    tags: ['affidavit', 'sworn', 'statement'],
    fields: [
      { name: 'deponent_name', label: 'Deponent Name', label_bn: 'হলফকারীর নাম', type: 'text', required: true },
      { name: 'deponent_father', label: "Deponent's Father's Name", label_bn: 'পিতার নাম', type: 'text', required: true },
      { name: 'age', label: 'Age', label_bn: 'বয়স', type: 'text', required: true },
      { name: 'religion', label: 'Religion', label_bn: 'ধর্ম', type: 'text', required: true },
      { name: 'profession', label: 'Profession', label_bn: 'পেশা', type: 'text', required: true },
      { name: 'deponent_address', label: 'Address', label_bn: 'ঠিকানা', type: 'textarea', required: true },
      { name: 'purpose', label: 'Purpose of Affidavit', label_bn: 'হলফনামার উদ্দেশ্য', type: 'text', required: true },
      { name: 'statement_1', label: 'Statement 1', label_bn: 'বিবৃতি ১', type: 'textarea', required: true },
      { name: 'statement_2', label: 'Statement 2', label_bn: 'বিবৃতি ২', type: 'textarea' },
      { name: 'statement_3', label: 'Statement 3', label_bn: 'বিবৃতি ৩', type: 'textarea' },
      { name: 'date', label: 'Date', label_bn: 'তারিখ', type: 'date', required: true },
      { name: 'place', label: 'Place', label_bn: 'স্থান', type: 'text', required: true },
    ],
  },
  {
    id: '8',
    template_name: 'Sale Deed',
    template_name_bn: 'বিক্রয় দলিল',
    category: 'property',
    template_type: 'Deed',
    template_content: `SALE DEED

This Sale Deed is executed on {{date}} at {{place}}

BETWEEN:

SELLER (First Party):
Name: {{seller_name}}
Father's Name: {{seller_father}}
Address: {{seller_address}}
NID: {{seller_nid}}

AND

BUYER (Second Party):
Name: {{buyer_name}}
Father's Name: {{buyer_father}}
Address: {{buyer_address}}
NID: {{buyer_nid}}

PROPERTY DETAILS:
Location: {{property_location}}
Mouza: {{mouza}}
J.L. No.: {{jl_no}}
C.S. Dag No.: {{cs_dag}}
S.A. Dag No.: {{sa_dag}}
R.S. Dag No.: {{rs_dag}}
Khatian No.: {{khatian_no}}
Total Land Area: {{land_area}}
Boundaries:
- North: {{north_boundary}}
- South: {{south_boundary}}
- East: {{east_boundary}}
- West: {{west_boundary}}

CONSIDERATION:
Total Sale Price: BDT {{sale_price}} ({{price_in_words}})
Paid as follows:
{{payment_details}}

TERMS:
1. The Seller hereby sells, transfers and conveys the above property to the Buyer.
2. The Seller declares having clear and marketable title.
3. The Seller has delivered possession to the Buyer.

SIGNATURES:

Seller: ____________________          Buyer: ____________________
({{seller_name}})                     ({{buyer_name}})

WITNESSES:
1. {{witness1_name}}                  2. {{witness2_name}}
   {{witness1_address}}                  {{witness2_address}}

---
Generated by JurisMind | Created by RONY`,
    tags: ['sale', 'property', 'deed'],
    fields: [
      { name: 'date', label: 'Deed Date', label_bn: 'দলিলের তারিখ', type: 'date', required: true },
      { name: 'place', label: 'Place of Execution', label_bn: 'সম্পাদনের স্থান', type: 'text', required: true },
      { name: 'seller_name', label: 'Seller Name', label_bn: 'বিক্রেতার নাম', type: 'text', required: true },
      { name: 'seller_father', label: "Seller's Father's Name", label_bn: 'বিক্রেতার পিতার নাম', type: 'text', required: true },
      { name: 'seller_address', label: 'Seller Address', label_bn: 'বিক্রেতার ঠিকানা', type: 'textarea', required: true },
      { name: 'seller_nid', label: 'Seller NID', label_bn: 'বিক্রেতার এনআইডি', type: 'text' },
      { name: 'buyer_name', label: 'Buyer Name', label_bn: 'ক্রেতার নাম', type: 'text', required: true },
      { name: 'buyer_father', label: "Buyer's Father's Name", label_bn: 'ক্রেতার পিতার নাম', type: 'text', required: true },
      { name: 'buyer_address', label: 'Buyer Address', label_bn: 'ক্রেতার ঠিকানা', type: 'textarea', required: true },
      { name: 'buyer_nid', label: 'Buyer NID', label_bn: 'ক্রেতার এনআইডি', type: 'text' },
      { name: 'property_location', label: 'Property Location', label_bn: 'সম্পত্তির অবস্থান', type: 'textarea', required: true },
      { name: 'mouza', label: 'Mouza', label_bn: 'মৌজা', type: 'text', required: true },
      { name: 'jl_no', label: 'J.L. No.', label_bn: 'জে.এল. নং', type: 'text', required: true },
      { name: 'cs_dag', label: 'C.S. Dag No.', label_bn: 'সি.এস. দাগ নং', type: 'text' },
      { name: 'sa_dag', label: 'S.A. Dag No.', label_bn: 'এস.এ. দাগ নং', type: 'text' },
      { name: 'rs_dag', label: 'R.S. Dag No.', label_bn: 'আর.এস. দাগ নং', type: 'text' },
      { name: 'khatian_no', label: 'Khatian No.', label_bn: 'খতিয়ান নং', type: 'text', required: true },
      { name: 'land_area', label: 'Land Area', label_bn: 'জমির পরিমাণ', type: 'text', required: true },
      { name: 'north_boundary', label: 'North Boundary', label_bn: 'উত্তরে', type: 'text', required: true },
      { name: 'south_boundary', label: 'South Boundary', label_bn: 'দক্ষিণে', type: 'text', required: true },
      { name: 'east_boundary', label: 'East Boundary', label_bn: 'পূর্বে', type: 'text', required: true },
      { name: 'west_boundary', label: 'West Boundary', label_bn: 'পশ্চিমে', type: 'text', required: true },
      { name: 'sale_price', label: 'Sale Price (BDT)', label_bn: 'বিক্রয় মূল্য', type: 'text', required: true },
      { name: 'price_in_words', label: 'Price in Words', label_bn: 'কথায় মূল্য', type: 'text', required: true },
      { name: 'payment_details', label: 'Payment Details', label_bn: 'পরিশোধের বিবরণ', type: 'textarea', required: true },
      { name: 'witness1_name', label: 'Witness 1 Name', label_bn: 'সাক্ষী ১', type: 'text', required: true },
      { name: 'witness1_address', label: 'Witness 1 Address', label_bn: 'সাক্ষী ১ ঠিকানা', type: 'text', required: true },
      { name: 'witness2_name', label: 'Witness 2 Name', label_bn: 'সাক্ষী ২', type: 'text', required: true },
      { name: 'witness2_address', label: 'Witness 2 Address', label_bn: 'সাক্ষী ২ ঠিকানা', type: 'text', required: true },
    ],
  },
];

const Templates = () => {
  const navigate = useNavigate();
  const { toast } = useToast();
  const [templates, setTemplates] = useState<Template[]>(sampleTemplates);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('all');
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [selectedTemplate, setSelectedTemplate] = useState<Template | null>(null);
  const [formData, setFormData] = useState<Record<string, string>>({});

  useEffect(() => {
    checkAuth();
    fetchTemplates();
  }, []);

  const checkAuth = async () => {
    const { data: { session } } = await supabase.auth.getSession();
    setIsAuthenticated(!!session);
  };

  const fetchTemplates = async () => {
    const { data, error } = await supabase
      .from('legal_templates')
      .select('*')
      .eq('is_public', true)
      .order('template_name');

    if (data && data.length > 0) {
      // Merge with sample templates that have field definitions
      const mergedTemplates = sampleTemplates.map(sample => {
        const dbTemplate = data.find(d => d.template_name === sample.template_name);
        return dbTemplate ? { ...sample, ...dbTemplate } : sample;
      });
      setTemplates(mergedTemplates);
    }
  };

  const filteredTemplates = templates.filter(template => {
    const matchesSearch = template.template_name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (template.template_name_bn && template.template_name_bn.includes(searchQuery));
    const matchesCategory = selectedCategory === 'all' || template.category === selectedCategory;
    return matchesSearch && matchesCategory;
  });

  const openTemplateForm = (template: Template) => {
    if (!isAuthenticated) {
      toast({
        title: "Authentication Required",
        description: "Please log in to use templates.",
        variant: "destructive",
      });
      navigate('/auth');
      return;
    }
    setSelectedTemplate(template);
    setFormData({});
  };

  const handleFieldChange = (fieldName: string, value: string) => {
    setFormData(prev => ({ ...prev, [fieldName]: value }));
  };

  const generateDocument = () => {
    if (!selectedTemplate) return;

    // Replace placeholders with form data
    let content = selectedTemplate.template_content;
    selectedTemplate.fields?.forEach(field => {
      const regex = new RegExp(`{{${field.name}}}`, 'g');
      content = content.replace(regex, formData[field.name] || `[${field.label}]`);
    });

    // Download the document
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${selectedTemplate.template_name.replace(/\s+/g, '_')}.txt`;
    a.click();
    URL.revokeObjectURL(url);

    toast({
      title: "Document Generated",
      description: `${selectedTemplate.template_name} has been downloaded.`,
    });

    setSelectedTemplate(null);
    setFormData({});
  };

  const getCategoryIcon = (category: string) => {
    const cat = templateCategories.find(c => c.id === category);
    return cat?.icon || FileText;
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 glass-panel border-b border-border">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3 cursor-pointer" onClick={() => navigate('/home')}>
            <div className="p-2 rounded-lg bg-gradient-to-br from-primary to-primary-glow">
              <Scale className="w-5 h-5 text-primary-foreground" />
            </div>
            <span className="text-xl font-bold bg-gradient-to-r from-primary to-legal-gold bg-clip-text text-transparent">
              JurisMind
            </span>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="ghost" onClick={() => navigate(isAuthenticated ? '/chat' : '/home')}>
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back
            </Button>
            {!isAuthenticated && (
              <Button className="glow-button bg-gradient-to-r from-primary to-primary-glow" onClick={() => navigate('/auth')}>
                Login
              </Button>
            )}
          </div>
        </div>
      </nav>

      <div className="pt-24 pb-12 px-4">
        <div className="container mx-auto">
          {/* Header */}
          <motion.div
            className="text-center mb-12"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
          >
            <h1 className="text-4xl font-bold mb-4">
              Legal <span className="text-primary">Templates</span>
            </h1>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              Access a comprehensive library of legal document templates for Bangladesh law.
              Fill in your details and download ready-to-use documents.
            </p>
          </motion.div>

          {/* Search and Filter */}
          <motion.div
            className="flex flex-col md:flex-row gap-4 mb-8"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.2 }}
          >
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search templates..."
                className="pl-10"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>
            <Select value={selectedCategory} onValueChange={setSelectedCategory}>
              <SelectTrigger className="w-full md:w-48">
                <Filter className="mr-2 h-4 w-4" />
                <SelectValue placeholder="Category" />
              </SelectTrigger>
              <SelectContent>
                {templateCategories.map(cat => (
                  <SelectItem key={cat.id} value={cat.id}>
                    {cat.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </motion.div>

          {/* Category Pills */}
          <ScrollArea className="w-full mb-8">
            <div className="flex gap-2 pb-2">
              {templateCategories.map(cat => (
                <Button
                  key={cat.id}
                  variant={selectedCategory === cat.id ? 'default' : 'outline'}
                  size="sm"
                  onClick={() => setSelectedCategory(cat.id)}
                  className={selectedCategory === cat.id ? 'bg-primary' : ''}
                >
                  <cat.icon className="mr-2 h-4 w-4" />
                  {cat.name}
                </Button>
              ))}
            </div>
          </ScrollArea>

          {/* Templates Grid */}
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filteredTemplates.map((template, index) => {
              const CategoryIcon = getCategoryIcon(template.category);
              return (
                <motion.div
                  key={template.id}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: index * 0.05 }}
                >
                  <Card className="p-6 glass-panel h-full flex flex-col hover:border-primary/50 transition-colors">
                    <div className="flex items-start justify-between mb-4">
                      <div className="p-3 rounded-lg bg-primary/10">
                        <CategoryIcon className="w-6 h-6 text-primary" />
                      </div>
                      <Badge variant="secondary">{template.template_type}</Badge>
                    </div>

                    <h3 className="text-lg font-bold mb-1">{template.template_name}</h3>
                    {template.template_name_bn && (
                      <p className="text-muted-foreground mb-3">{template.template_name_bn}</p>
                    )}

                    <div className="flex flex-wrap gap-1 mb-4">
                      {template.tags?.slice(0, 3).map(tag => (
                        <Badge key={tag} variant="outline" className="text-xs">
                          {tag}
                        </Badge>
                      ))}
                    </div>

                    <div className="mt-auto">
                      <Button
                        className="w-full"
                        onClick={() => openTemplateForm(template)}
                      >
                        <Download className="mr-2 h-4 w-4" />
                        Use Template
                      </Button>
                    </div>
                  </Card>
                </motion.div>
              );
            })}
          </div>

          {filteredTemplates.length === 0 && (
            <div className="text-center py-12">
              <FileText className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
              <p className="text-muted-foreground">No templates found matching your criteria.</p>
            </div>
          )}
        </div>
      </div>

      {/* Template Form Dialog */}
      <Dialog open={!!selectedTemplate} onOpenChange={() => setSelectedTemplate(null)}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <FileText className="h-5 w-5 text-primary" />
              {selectedTemplate?.template_name}
            </DialogTitle>
            {selectedTemplate?.template_name_bn && (
              <p className="text-muted-foreground">{selectedTemplate.template_name_bn}</p>
            )}
          </DialogHeader>

          <div className="space-y-4 py-4">
            {selectedTemplate?.fields?.map(field => (
              <div key={field.name} className="space-y-2">
                <Label htmlFor={field.name}>
                  {field.label}
                  {field.label_bn && <span className="text-muted-foreground ml-2">({field.label_bn})</span>}
                  {field.required && <span className="text-destructive ml-1">*</span>}
                </Label>
                {field.type === 'textarea' ? (
                  <Textarea
                    id={field.name}
                    value={formData[field.name] || ''}
                    onChange={(e) => handleFieldChange(field.name, e.target.value)}
                    placeholder={`Enter ${field.label.toLowerCase()}...`}
                    rows={3}
                  />
                ) : (
                  <Input
                    id={field.name}
                    type={field.type}
                    value={formData[field.name] || ''}
                    onChange={(e) => handleFieldChange(field.name, e.target.value)}
                    placeholder={`Enter ${field.label.toLowerCase()}...`}
                  />
                )}
              </div>
            ))}
          </div>

          <div className="flex gap-2 pt-4">
            <Button variant="outline" onClick={() => setSelectedTemplate(null)} className="flex-1">
              Cancel
            </Button>
            <Button onClick={generateDocument} className="flex-1 glow-button bg-gradient-to-r from-primary to-primary-glow">
              <Download className="mr-2 h-4 w-4" />
              Generate & Download
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* Footer */}
      <footer className="py-8 px-4 border-t border-border">
        <div className="container mx-auto text-center">
          <p className="text-muted-foreground">
            <span className="font-bold text-primary">JurisMind</span> — Created by RONY
          </p>
        </div>
      </footer>
    </div>
  );
};

export default Templates;